### ISSUE TITLE
with eslint

### ISSUE THREAD

**Issue by morelearn1990** [hannoeru/vite-plugin-pages#46] opened 2021-04-29 08:35 UTC
When I use eslint to check my code , this code will throw an eslint error。

`import routes from 'virtual:generated-pages';`

Unable to resolve path to module 'virtual:generated-pages'  import/no-unresolved

Do you have any good suggestions

**Comment by hannoeru** [comment] 2021-04-29 11:07
Duplicate of #41

**Closed by hannoeru** 2021-04-29 11:07 UTC
