### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by zhuhaobam** [hannoeru/vite-plugin-pages#280] opened 2022-08-27 05:29 UTC
### Describe the bug

[did].vue  After deploying on GitHub page
TypeError: Failed to fetch dynamically imported module: https://***/static/js/_did_-b317a9e4.js
There was no problem before. Was it the bug caused by your update in June

### Reproduction

TypeError: Failed to fetch dynamically imported module: https://***/static/js/_did_-b317a9e4.js

### System Info

```shell
TypeError: Failed to fetch dynamically imported module: https://***/static/js/_did_-b317a9e4.js
```

### Used Package Manager

pnpm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhuhaobam** [comment] 2022-08-27 05:35
I used another method
such as：
[did]
   index.vue
Change the original [did]. Vue into a folder [did], which contains index.vue

Is the bug caused by the new function

**Comment by hannoeru** [comment] 2022-08-27 07:51
Duplicate of #247

**Closed by hannoeru** 2022-08-27 07:51 UTC
